swagger: "2.0"
info:
  title: "URL-Shortener REST API"
  version: "0.0.1"
host: "demo.fatheroctober.com"
basePath: "/shorturl/v1"

schemes:
- "https"

paths:
  /shorten:
    post:
      operationId: shorten
      description: shorten a long URL
      tags:
        - shortener
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: longURL
          description: Long URL
          required: true
          schema:
            $ref: "#/definitions/URL"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/URL"
        400:
          description: "Bad format of request parameters"

  /{shortID}:
    get:
      operationId: forward
      description: forward to original long URL
      tags:
        - shortener
      produces:
      - "application/json"
      parameters:
      - in: "path"
        name: "shortID"
        type: "string"
        required: true
      responses:
        302:
          description: "Redirect to original URL"
        404:
          description: "Not found"

definitions:
  URL:
    type: "object"
    properties:
      value:
        type: "string"
        pattern: "^(http:\\/\\/www\\.|https:\\/\\/www\\.|http:\\/\\/|https:\\/\\/)?[a-z0-9]+([\\-\\.]{1}[a-z0-9]+)*\\.[a-z]{2,5}(:[0-9]{1,5})?(\\/.*)?$"
